package scenes;

import java.awt.Point;
import java.util.ArrayList;

import graph.AdjacencyList;
import graph.Vertex;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.RadioButton;
import javafx.scene.control.Toggle;
import javafx.scene.control.ToggleGroup;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Line;
import javafx.stage.Stage;
import pathfinder.Pathfinder;

public class GraphUI extends Stage {
	// Graph
	AdjacencyList graph;
	
	// Background image
	Image image;
	
	// To hold the radio buttons for event handling
	ToggleGroup tg;
	
	// Store last clicked 2 Points
	Point prevPoint;
	Point currentPoint;
	
	//  Group to be updated with Dijkstra result
	Pane pane;
	Group edges;
	Group result;
	Group rbuttons;
	
	// The offset to draw edges to center of RadioButtons instead of top left
	int rbOffset = 8;
	
    public GraphUI(AdjacencyList graph) {
    		this.graph = graph;
    		
    		// Initialize global variables
    		pane = new Pane();
    		
    		// Predefine a random path to draw
    		ArrayList<Vertex> vertices = graph.getPoints();
    		prevPoint = vertices.get((int) (Math.random() * vertices.size()));
    		currentPoint = vertices.get((int) (Math.random() * vertices.size()));
    	
    		// Create random graph to start with
    		drawGraph();
        Group g = new Group();
        g.getChildren().add(pane);
        Scene scene = new Scene(g, Color.BLACK);

        setTitle("Dijkstra"); 
        setFullScreen(true); 
        setScene(scene);
        show(); 
    }
    
    public void setImage(Image image) {
    	this.image = image;
    	drawGraph();
    }
    
    // Draw the graph given
	void drawGraph() {	
		pane.getChildren().clear();
		
		edges = edges();
		result = drawDijkstra();
		rbuttons = radioButtons();
		
		pane.getChildren().addAll(edges, new ImageView(image), result, rbuttons);
	}
	
	Group radioButtons() {
		// Draw vertices on Pane as Radio Buttons
		// The radio buttons serve as UI to select next destination
		Group buttons = new Group();
		tg = new ToggleGroup();
		
		for (Point parent : graph) {			
			RadioButton btn = new RadioButton(parent.toString());
			btn.setLayoutX(parent.getX());
			btn.setLayoutY(parent.getY());
			btn.setUserData(parent);
			btn.setToggleGroup(tg);
			buttons.getChildren().add(btn);
		}
		
	    tg.selectedToggleProperty().addListener(new ChangeListener<Toggle>() {
	    	@Override
	    	public void changed(ObservableValue<? extends Toggle> ov, Toggle old_toggle, Toggle new_toggle) {
	    		if (tg.getSelectedToggle() != null) {
	    			prevPoint = currentPoint;
					currentPoint = (Point) tg.getSelectedToggle().getUserData();
					System.out.println(String.format("Running points %s and %s through Dijkstra's algorithm", prevPoint, currentPoint));
					drawGraph();
	    		}
	        }
	    });
		
		return buttons;
	}
	
	Group edges() {
		// Display edges between vertices as grey lines
		Group edges = new Group();
		
		for (Point parent : graph) {
			for (Point child : graph.getPoint(parent).GetChildren()) {
				Line edge = new Line();
				edge.setStroke(Color.rgb(45, 45, 45));
				edge.setStrokeWidth(0.5);
				edge.setStartX(parent.getX() + rbOffset);
				edge.setStartY(parent.getY() + rbOffset);
				edge.setEndX(child.getX() + rbOffset);
				edge.setEndY(child.getY() + rbOffset);
				edges.getChildren().add(edge);
			}			
		}
		return edges;
	}
	
	Group drawDijkstra() {
		// Use Dijkstra to calculate path
		Point[] dijkstra = Pathfinder.dijkstra(graph, prevPoint, currentPoint);
		
		// Display path generated by Dijkstra as yellow lines
		Group path = new Group();
		
		for (int i = 0; i < dijkstra.length - 1; i++) {
			Line line = new Line();
			line.setStroke(Color.YELLOW);
			line.setStrokeWidth(2);
			line.setStartX(dijkstra[i].getX() + rbOffset);
			line.setStartY(dijkstra[i].getY() + rbOffset);
			line.setEndX(dijkstra[i+1].getX() + rbOffset);
			line.setEndY(dijkstra[i+1].getY() + rbOffset);
			path.getChildren().add(line);
		}
		
		return path;
	}
}
